//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubRenamerMAUI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubRenamerMAUI.Resources.Languages.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 清空列表 的本地化字符串。
        /// </summary>
        public static string btn_clear {
            get {
                return ResourceManager.GetString("btn_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入文件夹 的本地化字符串。
        /// </summary>
        public static string btn_open_folder {
            get {
                return ResourceManager.GetString("btn_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始重命名 的本地化字符串。
        /// </summary>
        public static string btn_start {
            get {
                return ResourceManager.GetString("btn_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你要清空列表吗？ 的本地化字符串。
        /// </summary>
        public static string clearconfirm1 {
            get {
                return ResourceManager.GetString("clearconfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空列表 的本地化字符串。
        /// </summary>
        public static string clearconfirm2 {
            get {
                return ResourceManager.GetString("clearconfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配 的本地化字符串。
        /// </summary>
        public static string col_matchkey {
            get {
                return ResourceManager.GetString("col_matchkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string col_status {
            get {
                return ResourceManager.GetString("col_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字幕 的本地化字符串。
        /// </summary>
        public static string col_sub {
            get {
                return ResourceManager.GetString("col_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string col_video {
            get {
                return ResourceManager.GetString("col_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你要丢弃选定项目的 的本地化字符串。
        /// </summary>
        public static string dropconfirm1 {
            get {
                return ResourceManager.GetString("dropconfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吗？源文件不会被删除 的本地化字符串。
        /// </summary>
        public static string dropconfirm2 {
            get {
                return ResourceManager.GetString("dropconfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丢弃所选项的 的本地化字符串。
        /// </summary>
        public static string dropconfirm3 {
            get {
                return ResourceManager.GetString("dropconfirm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请以.开头！ 的本地化字符串。
        /// </summary>
        public static string input_please_start_with_dot {
            get {
                return ResourceManager.GetString("input_please_start_with_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入字幕扩展名（以.开头） 的本地化字符串。
        /// </summary>
        public static string input_sub_ex {
            get {
                return ResourceManager.GetString("input_sub_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入视频扩展名（以.开头） 的本地化字符串。
        /// </summary>
        public static string input_video_ex {
            get {
                return ResourceManager.GetString("input_video_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配结果: 的本地化字符串。
        /// </summary>
        public static string manul_match_result {
            get {
                return ResourceManager.GetString("manul_match_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未匹配 的本地化字符串。
        /// </summary>
        public static string manul_unmatched {
            get {
                return ResourceManager.GetString("manul_unmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制改名命令至剪切板 的本地化字符串。
        /// </summary>
        public static string menu_copy_clipboard {
            get {
                return ResourceManager.GetString("menu_copy_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丢弃字幕 的本地化字符串。
        /// </summary>
        public static string menu_discard_sub {
            get {
                return ResourceManager.GetString("menu_discard_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丢弃视频 的本地化字符串。
        /// </summary>
        public static string menu_discard_video {
            get {
                return ResourceManager.GetString("menu_discard_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开字幕文件夹 的本地化字符串。
        /// </summary>
        public static string menu_open_sub_folder {
            get {
                return ResourceManager.GetString("menu_open_sub_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开视频文件夹 的本地化字符串。
        /// </summary>
        public static string menu_open_video_folder {
            get {
                return ResourceManager.GetString("menu_open_video_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string menu_remove {
            get {
                return ResourceManager.GetString("menu_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string menu_select_all {
            get {
                return ResourceManager.GetString("menu_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string preview_filename {
            get {
                return ResourceManager.GetString("preview_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改为 的本地化字符串。
        /// </summary>
        public static string preview_modify {
            get {
                return ResourceManager.GetString("preview_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (不修改) 的本地化字符串。
        /// </summary>
        public static string preview_no_modify {
            get {
                return ResourceManager.GetString("preview_no_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字幕 的本地化字符串。
        /// </summary>
        public static string preview_sub {
            get {
                return ResourceManager.GetString("preview_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string preview_video {
            get {
                return ResourceManager.GetString("preview_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你要删除选定的项目吗？ 的本地化字符串。
        /// </summary>
        public static string removeconfirm1 {
            get {
                return ResourceManager.GetString("removeconfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选项 的本地化字符串。
        /// </summary>
        public static string removeconfirm2 {
            get {
                return ResourceManager.GetString("removeconfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string status_failed {
            get {
                return ResourceManager.GetString("status_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已匹配 的本地化字符串。
        /// </summary>
        public static string status_matched {
            get {
                return ResourceManager.GetString("status_matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺字幕 的本地化字符串。
        /// </summary>
        public static string status_miss_sub {
            get {
                return ResourceManager.GetString("status_miss_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺视频 的本地化字符串。
        /// </summary>
        public static string status_miss_video {
            get {
                return ResourceManager.GetString("status_miss_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string status_success {
            get {
                return ResourceManager.GetString("status_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未匹配 的本地化字符串。
        /// </summary>
        public static string status_unmatched {
            get {
                return ResourceManager.GetString("status_unmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字幕 的本地化字符串。
        /// </summary>
        public static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字幕文件批量改名 (SubRenamer) 的本地化字符串。
        /// </summary>
        public static string title_subrenamer {
            get {
                return ResourceManager.GetString("title_subrenamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频文件批量改名 (VideoRenamer) 的本地化字符串。
        /// </summary>
        public static string title_videorenamer {
            get {
                return ResourceManager.GetString("title_videorenamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频或字幕文件 的本地化字符串。
        /// </summary>
        public static string video_or_subtitle_files {
            get {
                return ResourceManager.GetString("video_or_subtitle_files", resourceCulture);
            }
        }
    }
}
